default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Development")
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")
    gym(export_method: "ad-hoc",
        scheme: "AdHoc",
    )
  end

  desc "AppStore build and upload to TestFlight"
  lane :testflight do
    match(type: "appstore")
    build_app(scheme: "AppStore")
    upload_to_testflight
    #slack(message: "Successfully distributed a new TestFlight build")
  end
end