default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    lint
    #scan(scheme: "Development") // add this back when we have tests
    # in the meantime, build the app for PRs
    gym(
      scheme: "Development",
      skip_archive: true,
    )
  end

  desc "Run swiftlint"
  lane :lint do
    sh("brew install swiftlint")
    swiftlint(
      mode: :lint,      # SwiftLint mode: :lint (default) or :autocorrect
      ignore_exit_status: true    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
    )
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")

    increment_build_number(
      build_number: ENV['CIRCLE_BUILD_NUM'],
    )
    
    gym(export_method: "ad-hoc",
        scheme: "AdHoc",
    )
  end

  desc "AppStore build and upload to TestFlight"
  lane :buildanddeploytotestflight do
    match(type: "appstore")

    increment_build_number(
      build_number: ENV['CIRCLE_BUILD_NUM'],
    )

    build_app(scheme: "AppStore")
    upload_to_testflight
  end
end
