name: Pull Translations From Crowdin
on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner to use'
        required: false
        default: 'macos-latest'
        type: choice
        options:
          - macos-latest
          - self-hosted

jobs:
  synchronize-with-crowdin:
    runs-on: ${{ inputs.runner || vars.RUNNER_TYPE || 'macos-latest' }}
    environment: Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Crowdin CLI
        run: brew install crowdin
        shell: sh

      - name: Download Translations
        run: |
          crowdin bundle download ${{ vars.CROWDIN_BUNDLE_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          
      - name: Install bundler
        run: gem install bundler
            
      - name: Install dependencies
        run: bundle install
    
      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Import translations to project
        uses: ./.github/actions/run_lane
        with:
          # Use xcstrings_import for xcstrings bundles, xliff_import for XLIFF bundles
          lane: xcstrings_import

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.CROWDIN_PR_BOT_TOKEN }}
          commit-message: Update Localizations
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: crowdin/update-translations-bot
          base: develop
          delete-branch: true
          add-paths: |
            Vocable/**/*.xcstrings
            Vocable/**/*.strings
          title: '[CI] Update Localizations'
          body: |
            Automated localization update from Crowdin.
          labels: |
            localization
            automated
          draft: false