name: On release push
on:
  push:
    branches:
      - release.**
jobs:
  on_release_push:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit and UI tests
        uses: ./.github/actions/run_lane
        with:
          lane: test_unit_ui
          match_password: ${{ secrets.MATCH_PASSWORD }}

      - name: Commit translation file if changed
        uses: ./.github/actions/xliff_export

      - name: Build and deploy to TestFlight
        uses: ./.github/actions/run_lane
        with:
          lane: build_deploy_testflight
          match_password: ${{ secrets.MATCH_PASSWORD }}
